"use client";
import Link from "next/link";
import { ShoppingBag } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { CartLine } from "@/components/cart/cart-line";
import { formatCurrency } from "@/lib/format";
import { useCartStore } from "@/store/cart.store";
export function CartDrawer() { const items = useCartStore((s) => s.items); const open = useCartStore((s) => s.drawerOpen); const setOpen = useCartStore((s) => s.setDrawerOpen); const subtotal = items.reduce((sum, item) => sum + item.price * item.quantity, 0); return <Sheet open={open} onOpenChange={setOpen}><SheetContent className="w-full border-border bg-surface p-0 sm:max-w-md"><SheetHeader className="border-b border-border p-6"><SheetTitle className="heading flex items-center gap-2 text-xl"><ShoppingBag className="size-5 text-accent" />Your cart</SheetTitle><SheetDescription>{items.length ? `${items.length} distinct items ready to go.` : "Your loadout is waiting."}</SheetDescription></SheetHeader><div className="h-[calc(100vh-12rem)] overflow-y-auto px-6">{items.length ? items.map((item) => <CartLine key={item.productId} item={item} />) : <div className="grid h-full place-items-center text-center text-text-secondary"><div><ShoppingBag className="mx-auto mb-3 size-10 text-text-muted" /><p>Your cart is empty.</p></div></div>}</div>{items.length > 0 && <SheetFooter className="absolute inset-x-0 bottom-0 border-t border-border bg-surface p-6"><div className="mb-3 flex w-full justify-between font-semibold"><span>Subtotal</span><span>{formatCurrency(subtotal)}</span></div><Button asChild className="w-full" size="lg"><Link href="/checkout" onClick={() => setOpen(false)}>Checkout</Link></Button><Button asChild variant="ghost" className="w-full"><Link href="/cart" onClick={() => setOpen(false)}>View full cart</Link></Button></SheetFooter>}</SheetContent></Sheet>; }
