"use client";
import Link from "next/link";
import { signOut, useSession } from "next-auth/react";
import { Menu, ShoppingBag, UserRound, X } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Logo } from "@/components/layout/logo";
import { useCartStore } from "@/store/cart.store";
const categories = ["PlayStation", "Xbox", "Game Discs", "Controllers"];
export function Navbar() {
  const [mobileOpen, setMobileOpen] = useState(false); const items = useCartStore((s) => s.items); const setDrawerOpen = useCartStore((s) => s.setDrawerOpen); const { data: session } = useSession(); const user = session?.user; const count = items.reduce((total, item) => total + item.quantity, 0);
  return <header className="sticky top-0 z-40 border-b border-border bg-surface/85 backdrop-blur-xl"><div className="page-shell flex h-16 items-center justify-between gap-5"><Logo /><nav aria-label="Primary navigation" className="hidden items-center gap-6 lg:flex">{categories.map((category) => <Link key={category} href={`/?category=${encodeURIComponent(category)}`} className="text-sm text-text-secondary transition-colors hover:text-text-primary">{category}</Link>)}</nav><div className="flex items-center gap-1"><Button variant="ghost" size="icon" onClick={() => setDrawerOpen(true)} aria-label={`Open cart with ${count} items`} className="relative"><ShoppingBag className="size-5" />{count > 0 && <span className="absolute right-0 top-0 grid min-w-5 place-items-center rounded-full bg-accent px-1 text-[10px] font-bold text-white">{count}</span>}</Button>{user ? <DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" className="hidden gap-2 sm:flex" />}><UserRound className="size-4" />{user.name}</DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem render={<Link href="/orders" />}>My orders</DropdownMenuItem>{user.role === "ROLE_ADMIN" && <DropdownMenuItem render={<Link href="/admin" />}>Admin dashboard</DropdownMenuItem>}<DropdownMenuSeparator /><DropdownMenuItem onClick={() => void signOut({ redirectTo: "/" })}>Log out</DropdownMenuItem></DropdownMenuContent></DropdownMenu> : <Button asChild variant="ghost" className="hidden sm:flex"><Link href="/login">Log in</Link></Button>}<Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMobileOpen((open) => !open)} aria-expanded={mobileOpen} aria-label="Toggle navigation">{mobileOpen ? <X /> : <Menu />}</Button></div></div>{mobileOpen && <nav aria-label="Mobile navigation" className="page-shell grid gap-1 border-t border-border py-3 lg:hidden">{categories.map((category) => <Link onClick={() => setMobileOpen(false)} key={category} href={`/?category=${encodeURIComponent(category)}`} className="rounded-md px-3 py-2 text-text-secondary hover:bg-surface-2 hover:text-white">{category}</Link>)}{user ? <Link href="/orders" className="rounded-md px-3 py-2">My orders</Link> : <Link href="/login" className="rounded-md px-3 py-2">Log in</Link>}</nav>}</header>;
}
